source "$HOME/dotfiles/zsh/env.zsh"
source "$HOME/dotfiles/zsh/history.zsh"
source "$HOME/dotfiles/zsh/plugins.zsh"
source "$HOME/dotfiles/zsh/alias.zsh"
source "$HOME/dotfiles/zsh/keybinds.zsh"
source "$HOME/dotfiles/zsh/functions.zsh"
