#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# yabai -m config window_animation_duration    0.35

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:32:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:20:20


# yabai -m config active_window_border_color 0xffffffff
# yabai -m config normal_window_border_color 0xff555555 
# yabai -m config window_border on 
# yabai -m config window_border_width 2


# bsp or float (default: float)
yabai -m config layout bsp

yabai -m config window_placement second_child

# Padding
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

yabai -m config window_shadow float

yabai -m config window_opacity off

# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

# 设置不管理的应用
yabai -m rule --add app="^System Settings|系统设置$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^Clash Verge$" manage=off
yabai -m rule --add app="^网易云音乐$" manage=off
yabai -m rule --add app="^Raycast$" manage=off

echo "yabai configuration loaded.."

